language: java

jdk:
  -  openjdk11

branches:
    only:
        - master

install: cd iDrop && mvn install -DskipTests=true -Dmaven.javadoc.skip=true

script: mvn clean install

after_success:
  - cat target/surefire-reports/*.txt

after_failure:
  - cat target/surefire-reports/*.txt



